name = "final"
compatibility_date = "2023-10-01"

# Environment variables
[vars]
NODE_ENV = "production"

[[kv_namespaces]]
binding = "VIDEO_DATA"
id = "${VIDEO_DATA_KV_ID}"
preview_id = "${VIDEO_DATA_KV_PREVIEW_ID}"  # Preview namespace for local development 